name: push to ecr
on: [push]

jobs:
  buuld-python-slim:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Amazon ECR "Login" Action for GitHub Actions
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: build, tag and push image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: hematite/python-slim
        IMAGE_TAG: ${{ github.sha }}
      run:
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f py-slim.Dockerfile . 
          docker build $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

